<script setup>
import { computed } from 'vue';
import {
  AudioLines,
  Badge,
  BadgeCheck,
  Bell,
  BookOpen,
  Box,
  ChevronDown,
  ChevronUp,
  CircleDot,
  Compass,
  Copy,
  Crown,
  Download,
  Expand,
  ExternalLink,
  EyeOff,
  FolderOpen,
  Frown,
  Gift,
  Grid3X3,
  HandHeart,
  Heart,
  Home,
  ImageIcon,
  Laugh,
  List,
  LoaderCircle,
  Lock,
  Maximize,
  Meh,
  Menu,
  MessageCircle,
  Mic,
  MicOff,
  Monitor,
  MoreHorizontal,
  Moon,
  Music,
  Package,
  Palette,
  PanelLeft,
  Pause,
  Play,
  Radio,
  RefreshCw,
  Save,
  Search,
  Send,
  Settings,
  Settings2,
  SkipBack,
  SkipForward,
  Smile,
  SmilePlus,
  Sparkles,
  Star,
  StickyNote,
  Sun,
  Trash2,
  Upload,
  User,
  UserRound,
  Users,
  Volume2,
  WandSparkles,
  X
} from '@lucide/vue';

const props = defineProps({
  name: { type: String, required: true },
  size: { type: [Number, String], default: 20 },
  strokeWidth: { type: [Number, String], default: 2 }
});

const iconMap = {
  audioLines: AudioLines,
  badge: Badge,
  badgeCheck: BadgeCheck,
  bell: Bell,
  book: BookOpen,
  box: Box,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  circleDot: CircleDot,
  compass: Compass,
  copy: Copy,
  crown: Crown,
  download: Download,
  ellipsis: MoreHorizontal,
  expand: Expand,
  external: ExternalLink,
  eyeOff: EyeOff,
  folder: FolderOpen,
  frown: Frown,
  gamepad: Monitor,
  gift: Gift,
  grid: Grid3X3,
  handHeart: HandHeart,
  heart: Heart,
  home: Home,
  image: ImageIcon,
  laugh: Laugh,
  list: List,
  loader: LoaderCircle,
  lock: Lock,
  maximize: Maximize,
  meh: Meh,
  menu: Menu,
  message: MessageCircle,
  mic: Mic,
  micOff: MicOff,
  moon: Moon,
  music: Music,
  note: StickyNote,
  package: Package,
  palette: Palette,
  panelLeft: PanelLeft,
  pause: Pause,
  play: Play,
  plaza: Radio,
  radio: Radio,
  refresh: RefreshCw,
  save: Save,
  search: Search,
  send: Send,
  settings: Settings,
  settings2: Settings2,
  skipBack: SkipBack,
  skipForward: SkipForward,
  smile: Smile,
  smilePlus: SmilePlus,
  sparkles: Sparkles,
  star: Star,
  sun: Sun,
  trash: Trash2,
  upload: Upload,
  user: User,
  userRound: UserRound,
  users: Users,
  volume: Volume2,
  wand: WandSparkles,
  x: X
};

const icon = computed(() => iconMap[props.name] || Home);
</script>

<template>
  <component
    :is="icon"
    class="ts-icon"
    :data-icon-name="name"
    :size="size"
    :stroke-width="strokeWidth"
    aria-hidden="true"
  />
</template>
